---

- hosts: localhost
  vars:
    nios_provider:
      host: 192.168.201.151
      username: admin
      password: infoblox

  connection: local
  tasks:
   - name: create network
     infoblox.nios_modules.nios_network:
       network: 10.0.0.0/24
       network_view: ansibleCollectionsView
       options:
         - name: domain-name
           value: infoblox-ansible.com
       extattrs:
         Site: Test Site
       comment: Created with Ansible
       state: present
       provider: "{{ nios_provider }}"
